enum ActionTypes {
  DETECT_PREVIOUS_SESSION = 'Application/Session/DETECT_PREVIOUS_SESSION',
  DETECT_PREVIOUS_SESSION_FAILED = 'Application/Session/DETECT_PREVIOUS_SESSION_FAILED',
  VERIFY_PREVIOUS_SESSION = 'Application/Session/VERIFY_PREVIOUS_SESSION',
  VERIFY_PREVIOUS_SESSION_SUCCESS = 'Application/Session/VERIFY_PREVIOUS_SESSION_SUCCESS',
  VERIFY_PREVIOUS_SESSION_FAILED = 'Application/Session/VERIFY_PREVIOUS_SESSION_FAILED',
}

export default ActionTypes;
